export const BAUDRATE = [
  'AUTO',
  '1200',
  '2400',
  '4800',
  '9600',
  '19200',
  '38400',
  '57600',
  '115200',
  '230400',
  '250000',
  '460800',
  '921600'
]

export const PORT_NAME = {
  0: 'UART1',
  1: 'UART2',
  2: 'UART3',
  3: 'UART4',
  4: 'UART5',
  5: 'UART6',
  6: 'UART7',
  7: 'UART8',
  20: 'USB VCP',
  30: 'SOFTSERIAL1',
  31: 'SOFTSERIAL2'
}

export const PORT_FUNCTION_MASK = {
  MSP: 1 << 0,
  GPS: 1 << 1,
  TELEMETRY_FRSKY: 1 << 2,
  TELEMETRY_HOTT: 1 << 3,
  TELEMETRY_LTM: 1 << 4, // LTM replaced MSP
  TELEMETRY_SMARTPORT: 1 << 5,
  RX_SERIAL: 1 << 6,
  BLACKBOX: 1 << 7,
  TELEMETRY_MAVLINK: 1 << 8,
  TELEMETRY_IBUS: 1 << 9,
  RUNCAM_DEVICE_CONTROL: 1 << 10,
  TBS_SMARTAUDIO: 1 << 11,
  IRC_TRAMP: 1 << 12,
  OPFLOW: 1 << 14,
  LOG: 1 << 15,
  RANGEFINDER: 1 << 16,
  VTX_FFPV: 1 << 17,
  ESC: 1 << 18,
  GSM_SMS: 1 << 19,
  FRSKY_OSD: 1 << 20,
  DJI_FPV: 1 << 21,
  SMARTPORT_MASTER: 1 << 23,
}

export const TELEMETRY = {
  FRSKY: PORT_FUNCTION_MASK.TELEMETRY_FRSKY,
  HOTT: PORT_FUNCTION_MASK.TELEMETRY_HOTT,
  LTM: PORT_FUNCTION_MASK.TELEMETRY_LTM,
  SMARTPORT: PORT_FUNCTION_MASK.TELEMETRY_SMARTPORT,
  MAVLINK: PORT_FUNCTION_MASK.TELEMETRY_MAVLINK,
  IBUS: PORT_FUNCTION_MASK.TELEMETRY_IBUS,
  GSM_SMS: PORT_FUNCTION_MASK.GSM_SMS,
}

export const TELEMETRY_MASK = Object.values(TELEMETRY).reduce((acc, item) => acc | item, 0)

export const SENSOR = {
  GPS: PORT_FUNCTION_MASK.GPS,
  RANGEFINDER: PORT_FUNCTION_MASK.RANGEFINDER,
  OPFLOW: PORT_FUNCTION_MASK.OPFLOW,
}

export const SENSOR_MASK = Object.values(SENSOR).reduce((acc, item) => acc | item, 0)

export const PERIPHERAL = {
  BLACKBOX: PORT_FUNCTION_MASK.BLACKBOX,
  RUNCAM_DEVICE_CONTROL: PORT_FUNCTION_MASK.RUNCAM_DEVICE_CONTROL,
  TBS_SMARTAUDIO: PORT_FUNCTION_MASK.TBS_SMARTAUDIO,
  IRC_TRAMP: PORT_FUNCTION_MASK.IRC_TRAMP,
  VTX_FFPV: PORT_FUNCTION_MASK.VTX_FFPV,
  ESC: PORT_FUNCTION_MASK.ESC,
  FRSKY_OSD: PORT_FUNCTION_MASK.FRSKY_OSD,
  DJI_FPV: PORT_FUNCTION_MASK.DJI_FPV,
  SMARTPORT_MASTER: PORT_FUNCTION_MASK.SMARTPORT_MASTER,
}

export const PERIPHERAL_MASK = Object.values(PERIPHERAL).reduce((acc, item) => acc | item, 0)
